# Generated by Django 5.1.1 on 2024-09-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('numero_apartamento', models.CharField(max_length=3)),
                ('numero_telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7, unique=True)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_salida', models.DateTimeField(default=None)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.vehiculo')),
            ],
        ),
    ]
