# Generated by Django 5.1.1 on 2024-09-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='vehiculo',
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
