# Generated by Django 5.1.1 on 2024-09-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('numero_apartamento', models.CharField(max_length=3)),
                ('numero_telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
